name: Docker Image CI

on:
  push:
    tags:
      - '*'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: asia-northeast3
  REPOSITORY: demo
  IMAGE: sesacc
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Run chmod to make gradlew executable
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: echo '${{ secrets.GCP_SA_KEY }}' | docker login -u _json_key --password-stdin https://${{ env.GAR_LOCATION }}-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }} .
        docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }} 

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Deploy to GCP
      env:
        PRIVATE_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.GCP_HOST }}
        USER: ${{ secrets.GCP_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          cat ${{ secrets.GCP_KEY_PATH }} |  docker login -u _json_key --password-stdin https://asia-northeast3-docker.pkg.dev
        "
 
