name: Docker Image CI

on:
  push:
    tags:
      - '*'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: asia-northeast3
  REPOSITORY: demo
  IMAGE: sesacc
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Deploy to GCP
      env:
        PRIVATE_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.GCP_HOST }}
        USER: ${{ secrets.GCP_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          cat ${{ secrets.GCP_KEY_PATH }} | docker login -u _json_key_base64 --password-stdin https://asia-northeast3-docker.pkg.dev
          docker pull ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:71db098bff745d188474bc899aa504b17034a399
        '
 
